package chibivaru.additionalrecipe.event;

import chibivaru.additionalrecipe.AdditionalRecipe;
import cpw.mods.fml.common.ModMetadata;

public class ModInfo {
	public static void loadInfo(ModMetadata meta) {
		meta.modId = AdditionalRecipe.MODID;
		meta.name = AdditionalRecipe.MODNAME;
		meta.description ="This mod adds Additional Recipe for Minecraft.";
		meta.version =AdditionalRecipe.VERSION ;
		meta.url = "http://chaostcg31.blog.fc2.com/";
		meta.authorList.add("Chibivaru");
		meta.credits = "";
		//meta.logoFile ="assets/aluminiummod/logo.png";
		meta.logoFile = "";
		meta.autogenerated = false;
	}
 
}
